# Themes
PRODUCT_PACKAGES += \
    DUFonts

# Extended system fonts
PRODUCT_COPY_FILES += \
    vendor/themes/fonts/gobold/Gobold.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Gobold.ttf \
    vendor/themes/fonts/gobold/Gobold-Italic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Gobold-Italic.ttf \
    vendor/themes/fonts/gobold/GoboldBold.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoboldBold.ttf \
    vendor/themes/fonts/gobold/GoboldBold-Italic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoboldBold-Italic.ttf \
    vendor/themes/fonts/gobold/GoboldThinLight.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoboldThinLight.ttf \
    vendor/themes/fonts/gobold/GoboldThinLight-Italic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoboldThinLight-Italic.ttf \
    vendor/themes/fonts/ProductSans/ProductSans-Italic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ProductSans-Italic.ttf \
    vendor/themes/fonts/ProductSans/ProductSans-Light.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ProductSans-Light.ttf \
    vendor/themes/fonts/ProductSans/ProductSans-LightItalic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ProductSans-LightItalic.ttf \
    vendor/themes/fonts/ProductSans/ProductSans-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ProductSans-Regular.ttf \
    vendor/themes/fonts/ProductSans/ProductSans-Thin.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ProductSans-Thin.ttf \
    vendor/themes/fonts/ProductSans/ProductSans-ThinItalic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ProductSans-ThinItalic.ttf \
    vendor/themes/fonts/GoogleSans-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoogleSans-Regular.ttf \
    vendor/themes/fonts/GoogleSans-Medium.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoogleSans-Medium.ttf \
    vendor/themes/fonts/GoogleSans-MediumItalic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoogleSans-MediumItalic.ttf \
    vendor/themes/fonts/GoogleSans-Italic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoogleSans-Italic.ttf \
    vendor/themes/fonts/GoogleSans-Bold.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoogleSans-Bold.ttf \
    vendor/themes/fonts/GoogleSans-BoldItalic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GoogleSans-BoldItalic.ttf \
    vendor/themes/fonts/roadrage/road_rage.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/RoadRage-Regular.ttf \
    vendor/themes/fonts/neoneon/neoneon.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Neoneon-Regular.ttf \
    vendor/themes/fonts/mexcellent/mexcellent.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Mexcellent-Regular.ttf \
    vendor/themes/fonts/burnstown/burnstown.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Burnstown-Regular.ttf \
    vendor/themes/fonts/dumbledor/dumbledor.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Dumbledor-Regular.ttf \
    vendor/themes/fonts/PhantomBold/PhantomBold.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/PhantomBold-Regular.ttf \
    vendor/themes/fonts/snowstorm/snowstorm.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Snowstorm-Regular.ttf \
    vendor/themes/fonts/vcrosd/vcr_osd_mono.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ThemeableFont-Regular.ttf \
    vendor/themes/fonts/Shamshung/Shamshung.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Shamshung.ttf \
    vendor/themes/fonts/snowstorm/snowstorm.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Snowstorm-Regular.ttf \
    vendor/themes/fonts/vcrosd/vcr_osd_mono.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ThemeableClock-vcrosd.ttf \
    vendor/themes/fonts/fontage/AdamCGPro-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/AdamCGPro-Regular.ttf \
    vendor/themes/fonts/fontage/AlexanaNeue-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/AlexanaNeue-Regular.ttf \
    vendor/themes/fonts/fontage/AlienLeague-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/AlienLeague-Regular.ttf \
    vendor/themes/fonts/fontage/Azedo-Light.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Azedo-Light.ttf \
    vendor/themes/fonts/fontage/BigNoodleTilting-Italic.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/BigNoodleTilting-Italic.ttf \
    vendor/themes/fonts/fontage/BigNoodleTilting-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/BigNoodleTilting-Regular.ttf \
    vendor/themes/fonts/fontage/Biko-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Biko-Regular.ttf \
    vendor/themes/fonts/fontage/Blern-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Blern-Regular.ttf \
    vendor/themes/fonts/fontage/CoCoBiker-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/CoCoBiker-Regular.ttf \
    vendor/themes/fonts/fontage/Fester-Medium.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Fester-Medium.ttf \
    vendor/themes/fonts/fontage/GinoraSans-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/GinoraSans-Regular.ttf \
    vendor/themes/fonts/fontage/Inkferno-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Inkferno-Regular.ttf \
    vendor/themes/fonts/fontage/Instruction-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Instruction-Regular.ttf \
    vendor/themes/fonts/fontage/JackLane-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/JackLane-Regular.ttf \
    vendor/themes/fonts/fontage/Metropolis1920-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Metropolis1920-Regular.ttf \
    vendor/themes/fonts/fontage/Monad-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Monad-Regular.ttf \
    vendor/themes/fonts/fontage/Noir-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Noir-Regular.ttf \
    vendor/themes/fonts/fontage/North-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/North-Regular.ttf \
    vendor/themes/fonts/fontage/OutrunFuture-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/OutrunFuture-Regular.ttf \
    vendor/themes/fonts/fontage/Qontra-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Qontra-Regular.ttf \
    vendor/themes/fonts/fontage/Riviera-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Riviera-Regular.ttf \
    vendor/themes/fonts/fontage/FoxAndCat-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ThemeableDate-fc.ttf \
    vendor/themes/fonts/fontage/FoxAndCat-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ThemeableOwner-fc.ttf \
    vendor/themes/fonts/fontage/TheOutbox-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/TheOutbox-Regular.ttf \
    vendor/themes/fonts/fontage/Union-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Union-Regular.ttf \
    vendor/themes/fonts/fontagev2/Abel-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Abel-Regular.ttf \
    vendor/themes/fonts/fontagev2/AdventPro-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/AdventPro-Regular.ttf \
    vendor/themes/fonts/fontagev2/ArchivoNarrow-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ArchivoNarrow-Regular.ttf \
    vendor/themes/fonts/fontagev2/AutourOne-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/AutourOne-Regular.ttf \
    vendor/themes/fonts/fontagev2/Bariol-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Bariol-Regular.ttf \
    vendor/themes/fonts/fontagev2/BadScript-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/BadScript-Regular.ttf \
    vendor/themes/fonts/fontagev2/CherrySwash-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/CherrySwash-Regular.ttf \
    vendor/themes/fonts/fontagev2/Codystar.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Codystar.ttf \
    vendor/themes/fonts/fontagev2/IBMPlexMono.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/IBMPlexMono.ttf \
    vendor/themes/fonts/fontagev2/IBMPlexMono-Light.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/IBMPlexMono-Light.ttf \
    vendor/themes/fonts/fontagev2/Jura-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Jura-Regular.ttf \
    vendor/themes/fonts/fontagev2/KellySlab-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/KellySlab-Regular.ttf \
    vendor/themes/fonts/fontagev2/Pompiere-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Pompiere-Regular.ttf \
    vendor/themes/fonts/fontagev2/Raleway-Light.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Raleway-Light.ttf \
    vendor/themes/fonts/fontagev2/ReemKufi-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/ReemKufi-Regular.ttf \
    vendor/themes/fonts/fontagev2/Satisfy-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Satisfy-Regular.ttf \
    vendor/themes/fonts/fontagev2/SeaweedScript-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/SeaweedScript-Regular.ttf \
    vendor/themes/fonts/fontagev2/SedgwickAveDisplay-Regular.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/SedgwickAveDisplay-Regular.ttf \
    vendor/themes/fonts/fontagev2/Vibur.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Vibur.ttf \
    vendor/themes/fonts/fontagev2/Voltaire.ttf:$(TARGET_COPY_OUT_SYSTEM)/fonts/Voltaire.ttf
